#############################################################################
# Makefile for building: editor
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Feb 6 00:45:00 2011
# Project:  lgmx.pro
# Template: app
# Command: /home/lgm/qtsdk-2010.05/qt/bin/qmake -o Makefile lgmx.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/lgm/qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I/home/lgm/qtsdk-2010.05/qt/include/QtCore -I/home/lgm/qtsdk-2010.05/qt/include/QtGui -I/home/lgm/qtsdk-2010.05/qt/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/lgm/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/lgm/qtsdk-2010.05/qt/lib -lQtGui -L/home/lgm/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/lgm/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ui_main_window.cpp \
		editor.cpp \
		code_editor.cpp \
		file.cpp \
		src_area.cpp \
		highlight/cpp_hl.cpp \
		go_to_line.cpp \
		src_file.cpp moc_code_editor.cpp \
		moc_ui_main_window.cpp \
		moc_cpp_hl.cpp \
		moc_go_to_line.cpp
OBJECTS       = main.o \
		ui_main_window.o \
		editor.o \
		code_editor.o \
		file.o \
		src_area.o \
		cpp_hl.o \
		go_to_line.o \
		src_file.o \
		moc_code_editor.o \
		moc_ui_main_window.o \
		moc_cpp_hl.o \
		moc_go_to_line.o
DIST          = /home/lgm/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/release.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		lgmx.pro
QMAKE_TARGET  = editor
DESTDIR       = 
TARGET        = editor

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: lgmx.pro  /home/lgm/qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf /home/lgm/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/release.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/home/lgm/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/home/lgm/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/home/lgm/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -o Makefile lgmx.pro
/home/lgm/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/home/lgm/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/release.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/home/lgm/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/home/lgm/qtsdk-2010.05/qt/lib/libQtGui.prl:
/home/lgm/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile lgmx.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/editor1.0.0 || $(MKDIR) .tmp/editor1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/editor1.0.0/ && $(COPY_FILE) --parents editor.h code_editor.h ui_main_window.h file.h src_area.h highlight/cpp_hl.h go_to_line.h ui_go_to_line.h src_file.h .tmp/editor1.0.0/ && $(COPY_FILE) --parents main.cpp ui_main_window.cpp editor.cpp code_editor.cpp file.cpp src_area.cpp highlight/cpp_hl.cpp go_to_line.cpp src_file.cpp .tmp/editor1.0.0/ && (cd `dirname .tmp/editor1.0.0` && $(TAR) editor1.0.0.tar editor1.0.0 && $(COMPRESS) editor1.0.0.tar) && $(MOVE) `dirname .tmp/editor1.0.0`/editor1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/editor1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_code_editor.cpp moc_ui_main_window.cpp moc_cpp_hl.cpp moc_go_to_line.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_code_editor.cpp moc_ui_main_window.cpp moc_cpp_hl.cpp moc_go_to_line.cpp
moc_code_editor.cpp: code_editor.h
	/home/lgm/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) code_editor.h -o moc_code_editor.cpp

moc_ui_main_window.cpp: code_editor.h \
		src_area.h \
		highlight/cpp_hl.h \
		src_file.h \
		go_to_line.h \
		ui_go_to_line.h \
		ui_main_window.h
	/home/lgm/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) ui_main_window.h -o moc_ui_main_window.cpp

moc_cpp_hl.cpp: highlight/cpp_hl.h
	/home/lgm/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) highlight/cpp_hl.h -o moc_cpp_hl.cpp

moc_go_to_line.cpp: ui_go_to_line.h \
		go_to_line.h
	/home/lgm/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) go_to_line.h -o moc_go_to_line.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ui_main_window.h \
		code_editor.h \
		src_area.h \
		highlight/cpp_hl.h \
		src_file.h \
		go_to_line.h \
		ui_go_to_line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ui_main_window.o: ui_main_window.cpp ui_main_window.h \
		code_editor.h \
		src_area.h \
		highlight/cpp_hl.h \
		src_file.h \
		go_to_line.h \
		ui_go_to_line.h \
		editor.h \
		file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ui_main_window.o ui_main_window.cpp

editor.o: editor.cpp editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editor.o editor.cpp

code_editor.o: code_editor.cpp code_editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o code_editor.o code_editor.cpp

file.o: file.cpp file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file.o file.cpp

src_area.o: src_area.cpp src_area.h \
		code_editor.h \
		highlight/cpp_hl.h \
		src_file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src_area.o src_area.cpp

cpp_hl.o: highlight/cpp_hl.cpp highlight/cpp_hl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cpp_hl.o highlight/cpp_hl.cpp

go_to_line.o: go_to_line.cpp go_to_line.h \
		ui_go_to_line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o go_to_line.o go_to_line.cpp

src_file.o: src_file.cpp src_file.h \
		code_editor.h \
		highlight/cpp_hl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src_file.o src_file.cpp

moc_code_editor.o: moc_code_editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_code_editor.o moc_code_editor.cpp

moc_ui_main_window.o: moc_ui_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ui_main_window.o moc_ui_main_window.cpp

moc_cpp_hl.o: moc_cpp_hl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cpp_hl.o moc_cpp_hl.cpp

moc_go_to_line.o: moc_go_to_line.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_go_to_line.o moc_go_to_line.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

